In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [3]:
dfconsumo=pd.read_excel('tablasConcatenadas.xlsx')
#dfconsumo.tail()

FileNotFoundError: [Errno 2] No such file or directory: 'tablasConcatenadas.xlsx'

In [4]:
null_columns = dfconsumo.columns[dfconsumo.isnull().any()]
dfconsumo[null_columns].isnull().sum()
print(dfconsumo[dfconsumo.isnull().any(axis=1)][null_columns].head())

      COCS.COCS-MT-01\nReal Power\n(kW)  COCS.COCS-TR-01\nReal Power\n(kW)  \
41                                  NaN                                NaN
734                                 NaN                         231.300491
758                                 NaN                           6.228995
759                               677.0                                NaN
1042                                NaN                          40.261272

      COCS.COCS-TR-02\nReal Power\n(kW)  COCS.COCS-TR-03\nReal Power\n(kW)  \
41                                  NaN                                NaN
734                          224.009262                         314.573792
758                           53.373058                         294.583374
759                                 NaN                                NaN
1042                         171.504791                         241.091141

      COCS.COCS-TR-04\nReal Power\n(kW)
41                                  NaN
734                          386.557159
758                          131.181381
759                                 NaN
1042                         239.977982

In [5]:
for col in list(dfconsumo.columns)[1:]:
    for i in range(len(dfconsumo[col])):
        if np.isnan(dfconsumo[col][i]):
            if i == 0:
                dfconsumo[col][i] = dfconsumo[col][i+1]
            elif i == len(dfconsumo[col]) - 1:
                dfconsumo[col][i] = dfconsumo[col][i-1]
            else:
                dfconsumo[col][i] = (dfconsumo[col][i+1] + dfconsumo[col][i-1])/2

dfconsumo

C:\Users\adiav\AppData\Local\Temp/ipykernel_9528/1311653952.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfconsumo[col][i] = (dfconsumo[col][i+1] + dfconsumo[col][i-1])/2

,Timestamp,COCS.COCS-MT-01\nReal Power\n(kW),COCS.COCS-TR-01\nReal Power\n(kW),COCS.COCS-TR-02\nReal Power\n(kW),COCS.COCS-TR-03\nReal Power\n(kW),COCS.COCS-TR-04\nReal Power\n(kW)
0,1/4/2021 00:15:00,331.0,4.361937,33.411430,106.244453,57.942059
1,1/4/2021 00:30:00,328.0,4.283674,34.312851,111.728188,53.709923
2,1/4/2021 00:45:00,295.0,4.216628,38.764618,87.968132,53.937267
3,1/4/2021 01:00:00,318.0,4.162058,33.617935,100.776886,56.016811
4,1/4/2021 01:15:00,266.0,4.255610,34.056599,92.210991,44.739353
...,...,...,...,...,...,...
2880,30/4/2021 23:00:00,473.0,18.870539,36.193127,113.411385,173.670151
2881,30/4/2021 23:15:00,383.0,4.680104,31.602556,129.369339,94.093224
2882,30/4/2021 23:30:00,386.0,4.341129,33.388958,133.955353,76.787117
2883,30/4/2021 23:45:00,333.0,4.305457,31.554388,95.567055,69.258896
2884,1/5/2021 00:00:00,299.0,4.358453,32.862667,97.251442,64.385864

In [5]:
#no se completan los datos cuando hay varias filas vacías no puede calcular sobre ceros
dfconsumo.to_excel('2104_lleno.xlsx', index=False)

In [6]:
#enlas celdas de las filas vacías de corrido completa con el promedio de la columna
dfconsumo = dfconsumo.fillna(dfconsumo.mean())

C:\Users\adiav\AppData\Local\Temp/ipykernel_9528/1795052397.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dfconsumo = dfconsumo.fillna(dfconsumo.mean())

In [7]:

dfconsumo.to_excel('2104_prom.xlsx', index=False)

In [8]:
#comprobamos que no hay nulls
null_columns = dfconsumo.columns[dfconsumo.isnull().any()]
dfconsumo[null_columns].isnull().sum()
print(dfconsumo[dfconsumo.isnull().any(axis=1)][null_columns].head())

Empty DataFrame
Columns: []
Index: []

In [9]:
#Agregamos columnas Suma TRs y atribuimos la diferencia con MT por consumo Cine

dfconsumo['Suma-TR-1,2,3,4-(Kw)']=dfconsumo.loc[:, [
    'COCS.COCS-TR-01\nReal Power\n(kW)', 'COCS.COCS-TR-02\nReal Power\n(kW)', 'COCS.COCS-TR-03\nReal Power\n(kW)', 'COCS.COCS-TR-04\nReal Power\n(kW)']].sum(axis=1)
dfconsumo['Diferencia_cine']=dfconsumo.loc[:, 'COCS.COCS-MT-01\nReal Power\n(kW)'] - dfconsumo.loc[:,'Suma-TR-1,2,3,4-(Kw)']
df_sumaTR_dif_cine=dfconsumo
df_sumaTR_dif_cine.head()

,Timestamp,COCS.COCS-MT-01\nReal Power\n(kW),COCS.COCS-TR-01\nReal Power\n(kW),COCS.COCS-TR-02\nReal Power\n(kW),COCS.COCS-TR-03\nReal Power\n(kW),COCS.COCS-TR-04\nReal Power\n(kW),"Suma-TR-1,2,3,4-(Kw)",Diferencia_cine
0,1/4/2021 00:15:00,331.0,4.361937,33.411430,106.244453,57.942059,201.959879,129.040121
1,1/4/2021 00:30:00,328.0,4.283674,34.312851,111.728188,53.709923,204.034635,123.965365
2,1/4/2021 00:45:00,295.0,4.216628,38.764618,87.968132,53.937267,184.886645,110.113355
3,1/4/2021 01:00:00,318.0,4.162058,33.617935,100.776886,56.016811,194.573691,123.426309
4,1/4/2021 01:15:00,266.0,4.255610,34.056599,92.210991,44.739353,175.262553,90.737447

In [10]:
#Promedios consumos con suma TRs y diferencia cine

dfProm_sumaTR_dif_cine = df_sumaTR_dif_cine.fillna(df_sumaTR_dif_cine.mean())
dfProm_sumaTR_dif_cine.head()

C:\Users\adiav\AppData\Local\Temp/ipykernel_9528/3005460783.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dfProm_sumaTR_dif_cine = df_sumaTR_dif_cine.fillna(df_sumaTR_dif_cine.mean())

,Timestamp,COCS.COCS-MT-01\nReal Power\n(kW),COCS.COCS-TR-01\nReal Power\n(kW),COCS.COCS-TR-02\nReal Power\n(kW),COCS.COCS-TR-03\nReal Power\n(kW),COCS.COCS-TR-04\nReal Power\n(kW),"Suma-TR-1,2,3,4-(Kw)",Diferencia_cine
0,1/4/2021 00:15:00,331.0,4.361937,33.411430,106.244453,57.942059,201.959879,129.040121
1,1/4/2021 00:30:00,328.0,4.283674,34.312851,111.728188,53.709923,204.034635,123.965365
2,1/4/2021 00:45:00,295.0,4.216628,38.764618,87.968132,53.937267,184.886645,110.113355
3,1/4/2021 01:00:00,318.0,4.162058,33.617935,100.776886,56.016811,194.573691,123.426309
4,1/4/2021 01:15:00,266.0,4.255610,34.056599,92.210991,44.739353,175.262553,90.737447

In [11]:
dfProm_sumaTR_dif_cine.to_excel('Prom_Compl_2104.xlsx',index=False)

In [12]:
df_sumaTR_dif_cine['Timestamp'] = pd.to_datetime(
    df_sumaTR_dif_cine['Timestamp'])
df_sumaTR_dif_cine = df_sumaTR_dif_cine.groupby(
    [df_sumaTR_dif_cine['Timestamp'].dt.date, df_sumaTR_dif_cine['Timestamp'].dt.hour]).mean()

In [13]:
df_sumaTR_dif_cine

                      COCS.COCS-MT-01\nReal Power\n(kW)  \
Timestamp  Timestamp
2021-01-04 0                                     318.00
           1                                     283.25
           2                                     262.00
           3                                     262.25
           4                                     254.50
...                                                 ...
2021-12-04 19                                    944.50
           20                                    884.25
           21                                    693.00
           22                                    475.25
           23                                    379.75

                      COCS.COCS-TR-01\nReal Power\n(kW)  \
Timestamp  Timestamp
2021-01-04 0                                   4.287413
           1                                   4.235417
           2                                   4.314738
           3                                   4.309554
           4                                   4.222909
...                                                 ...
2021-12-04 19                                 76.838736
           20                                 57.827473
           21                                 28.215156
           22                                  9.681726
           23                                  9.184249

                      COCS.COCS-TR-02\nReal Power\n(kW)  \
Timestamp  Timestamp
2021-01-04 0                                  35.496300
           1                                  34.375046
           2                                  36.757257
           3                                  33.667495
           4                                  33.963629
...                                                 ...
2021-12-04 19                                167.505371
           20                                164.482620
           21                                 77.479522
           22                                 40.976582
           23                                 36.013452

                      COCS.COCS-TR-03\nReal Power\n(kW)  \
Timestamp  Timestamp
2021-01-04 0                                 101.980258
           1                                 100.864744
           2                                 101.914867
           3                                 109.414841
           4                                 106.610529
...                                                 ...
2021-12-04 19                                289.284019
           20                                302.027176
           21                                279.609585
           22                                185.721704
           23                                115.121984

                      COCS.COCS-TR-04\nReal Power\n(kW)  Suma-TR-1,2,3,4-(Kw)  \
Timestamp  Timestamp
2021-01-04 0                                  55.196416            196.960387
           1                                  48.259688            187.734895
           2                                  41.221738            184.208600
           3                                  39.915159            187.307048
           4                                  39.958235            184.755302
...                                                 ...                   ...
2021-12-04 19                                253.985649            787.613775
           20                                208.323597            732.660866
           21                                159.677359            544.981622
           22                                107.369387            343.749399
           23                                 84.004099            244.323784

                      Diferencia_cine
Timestamp  Timestamp
2021-01-04 0               121.039613
           1                95.515105
           2                77.791400
           3                74.942952
           4                69.744698
...                               ...
2021-12-04 19              156.886225
           20              151.589134
           21              148.018378
           22              131.500601
           23              135.426216

[721 rows x 7 columns]

In [15]:
null_columns = df_sumaTR_dif_cine.columns[df_sumaTR_dif_cine.isnull().any()]
df_sumaTR_dif_cine[null_columns].isnull().sum()
print(df_sumaTR_dif_cine[df_sumaTR_dif_cine.isnull().any(
    axis=1)][null_columns].head())

Empty DataFrame
Columns: []
Index: []